# Generated by Django 4.2.4 on 2023-08-20 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_color_item_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='name',
        ),
    ]
